### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kbarbary** [kbarbary/bsplines#1]
- [x] out of range behavior options in 1-d spline: constant (default= knot value), extrapolate, error
- [x] error messaging
- [x] prettify exterior behavior and boundary conditions parameters in Python interface
- [x] more C tests for basis functions
- [x] continuous 3rd derivative ("not-a-knot") BC option
- [x] uniform 1-d spline
- [x] 2-d spline
- [x] handle `constant` extend (different from `value` for 2-d)
- [x] vector derivative BC in 2-d spline
- [x] need to use `np.require` for C continguousness? No.
- [x] checks for length of input arrays
  - minimum: 2 points
  - one not-a-knot: need 3 points
  - both not-a-knot: need 4 points (with 3 points, left and right conditions are the same).
- [ ] add Python tests from scipy interpolate
- [ ] benchmark 2-d spline
- [ ] uniform 2-d spline
- [ ] SIMD
  - check AVX at runtime: [stack overflow](http://stackoverflow.com/questions/6121792/how-to-check-if-a-cpu-supports-the-sse3-instruction-set) [crc32 example](https://github.com/JuliaLang/julia/pull/18297)
  - check at compile time: `$ gcc -march=native -dM -E - < /dev/null | egrep "SSE|AVX" | sort` shows that `__AVX__` will be defined by gcc.
  - [AVX matrix multiply example](https://gist.github.com/rygorous/4172889)
  - AVX intrinsics: https://software.intel.com/en-us/node/524038
  - `_mm256_loadu_pd` load 4 doubles
  - `_mm256_mul_pd` vector multiply
  - `_mm256_hadd_pd` add adjacent pairs
  - [SO answer on _mm256 dot product](http://stackoverflow.com/questions/10454150/intel-avx-256-bits-version-of-dot-product-for-double-precision-floating-point)
  - checking AVX at runtime might not work because if it doesn't exist, compiling with AVX support might generate code elsewhere (besides intrinsics) that depends on AVX.

**Comment by tkelman** [comment]
Note that AVX also requires OS support in addition to the cpu, see https://github.com/matthew-brett/libx86cpu/blob/master/os_restores_ymm.c
